### PR TITLE
React capstone project - Metrics webapp PR

### PR DESCRIPTION
**Pull request by AmaduKamara**
# React capstone project - Metrics webapp

I have implemented all requirements for this capstone project

- [ ] Use React documentation.
- [ ] Use React components.
- [ ] Use React props.
- [ ] Use React Router.
- [ ] Connect React and Redux.
- [ ] Handle events in a React app.
- [ ] Write integration tests with a React testing library.
- [ ] Use styles in a React app.
- [ ] Use React life cycle methods.
- [ ] Apply React best practices and language style guides in code.
- [ ] Use store, actions, and reducers in React.

### CODE REVIEW

**Review by uwadonat — CHANGES_REQUESTED** [review]
Hi **[AmaduKamara](https://github.com/AmaduKamara)** :hand: 

Good job so far! :mechanical_arm:
There are some issues that you still need to work on to go to the next project but you are almost there!

### To highlight! :+1: 
- You implemented most of the project requirements ✔️
- Good presentation ✔️

## Status: Required Changes ♻️

- [x] There is error in your test. kindly fix it

Screenshot from 2022-02-04 12-18-38

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by AmaduKamara** [comment]
Yeah sorry about that. I made an update after sending it for review and that caused the error. But it's fixed now. Thank you 🤝

**Review by DeliceLydia — APPROVED** [review]
# Congratulations🎉🎉

## Hi @AmaduKamara, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard).. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AmaduKamara** [comment]
Thank you!

**Pull request merged**
